name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          echo "Navigating to deployment directory..."
          sudo mkdir -p /var/www/frontend
          sudo chown -R ubuntu:ubuntu /var/www/frontend
          cd /var/www/frontend

          echo "Fetching latest code..."
          if [ -d .git ]; then
            git fetch origin main && git reset --hard origin/main
          else
            git clone https://github.com/${{ github.repository }} . || echo "Clone skipped"
          fi

          echo "Cleaning old build files..."
          rm -rf dist node_modules

          echo "Installing Node.js via NVM..."
          export NVM_DIR="\$HOME/.nvm"
          if [ ! -d "\$NVM_DIR" ]; then
            mkdir -p "\$NVM_DIR"
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          fi
          [ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
          nvm install 22
          nvm use 22

          echo "Installing dependencies..."
          npm install --legacy-peer-deps

          echo "Creating .env file from GitHub secret..."
          if [ -n "${{ secrets.FRONTEND_ENV_FILE }}" ]; then
            echo "${{ secrets.FRONTEND_ENV_FILE }}" > .env
            echo ".env file created."
          else
            echo "No FRONTEND_ENV_FILE found — skipping .env creation."
          fi

          echo "Building frontend..."
          npm run build

          echo "Verifying dist folder..."
          if [ ! -d "dist" ]; then
            echo "Build failed — dist not found!"
            exit 1
          fi

          echo "Deploying built files to Nginx root..."
          sudo rm -rf /var/www/frontend/*
          sudo cp -r dist/* /var/www/frontend/

          echo "Reloading Nginx..."
          sudo nginx -t && sudo systemctl reload nginx

          echo "Deployment completed successfully!"
          EOF
